# Option-1 : Createting docker image using command module 
---
- hosts: all
  become: true
  tasks:
  - name: building docker image
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /opt/docker
  - name: create tag to image
    command:docker tag simple-devops-image chenyi/simple-devops-image
  - name: push image on to dockerhub
    command:docker push chenyi/simple-devops-image
    
  -name: remove docker images from ansible server
    command:docker rmi simple-devops-image:latest chenyi/simple-devops-image
    ignore_errors: yes
    
# option-2 : creating docker image using docker_image module 

#  tasks:
#  - name: building docker image
#    docker_image:
#      build:
#        path: /opt/docker
#      name: simple-devops-image
#     tag: v1
#     source: build
